### PR TITLE
action-request-password-reset: Use crypto.randomBytes for reset token

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Instead of using a combination of the existing password and a secret env
var, just generate a buffer of random bytes and transform to a hex
string. Much simpler!

Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by ramirogm** [comment]
👀

**Comment by ramirogm** [comment]
@LucianBuzzo @Ereski Working on this issue.

The change broke some tests. The tests that broke depended on the resetToken being calculated from the user hash :/ They query for a `password-reset@1.0.0` with `resetToken` being equal to `request.arguments.resetToken`.

And those tests include a copy the code that we replaced to calculate the resetToken:

```ts
const hash = 'foobar';
const resetToken = crypto
	.createHmac('sha256', ACTIONS.resetPasswordSecretToken)
	.update(hash)
	.digest('hex');
```
See [this test](https://github.com/product-os/jellyfish-plugin-default/blob/master/test/integration/actions/action-complete-password-reset.spec.ts#L17)


Now I'm trying to fix the tests looking for the `password-reset@1.0.0`  cards using the `user` to filter. There's only one anyway since the tests clean up the DB but... seems cleaner this way

**Comment by ramirogm** [comment]
Changed the test logic, now getting the `resetToken` from the email which is sent to the user

**Comment by LucianBuzzo** [comment]
Nice @ramirogm this is much better 👍

**Comment by LucianBuzzo** [comment]
@balena-ci I self-certify!

**Pull request merged**
